- members/2k4sm.md
This PR adds `2k4sm.md` to [members](https://github.com/SST-OSS/club-onboarding/tree/main/members) folder.
Fixes: #1
> adds member 2k4sm

- members/Om-Midya.md
This PR add Om-Midya to members folder
Fix #1
> Added my Github_Handle

- members/narasimha-1511.md
This adds the file narasimha-1511.md to the directory 'members'.
This fixes the issue : https://github.com/SST-OSS/club-onboarding/issues/1
> This adds my github handle

- members/abhinavgupta-de.md
- notes/basic-commands.md
- notes/chmod.md
- notes/vim.md
Added notes of CLI for next task
> Documentation task

- members/PulsatingGenius.md
Fixes https://github.com/SST-OSS/club-onboarding/issues/1
What does this implement/fix?
This pr adds a new file PulsatingGenius.md inside folder [members](https://github.com/SST-OSS/club-onboarding/tree/main/members) that contains my github handle and my name
> Added-my-github-Handle

- members/varundeepsaini.md
Description:
This pull request adds a new member file under the members folder as mentioned in #1 . The file is named ```varundeepsaini.md``` and contains my name and Github Username.
Changes:
- Added ```varundeepsaini.md``` in the [members](https://github.com/SST-OSS/club-onboarding/tree/main/members) folder.
> Add Member Profile: Varun Deep Saini

- javaProblems/problem1/Solution.java
- javaProblems/problem2/Solution.java
- members/narasimha-1511.md
Successfully Completed the Solution
> Solution to problem 1 in Java Problems

- members/Sam-wiz.md
This PR is raised to add Sam-wiz.md to members folder with respect to the issue https://github.com/SST-OSS/club-onboarding/issues/1
Thank You
> Added my file Sam-wiz.md in members folder

- members/abhinavgupta-de.md
> Abhinav Gupta

- notes/basic-commands.md
This corrects the spelling mistake in the line 5 in the word 'print'.
This fixes #15
> This corrects the error in the line 5 of the file basic-commands.md

- javaProblems/problem4/Solution.java
This is the Solution to Problem No:4
> Solution to Java Problem 4

- members/Krupakar-Reddy-S.md
New member added, Krupakar-Reddy-S
Fixes issue: [#1](https://github.com/SST-OSS/club-onboarding/issues/1)
> New member: Krupakar-Reddy-S

- members/attaditya.md
- Created file "members/attaditya.md" for the issue - [Club Member Request ](https://github.com/SST-OSS/club-onboarding/issues/1)
> Aditya's member request

- members/srujan0404.md
Created file **`members/srujan0404.md`** for the issue - https://github.com/SST-OSS/club-onboarding/issues/1
> added srujan0404.md to 

- members/krishna-p060.md
Added member Krishna Patidar
fixes #1
> Added info in member folder

- javaProblems/problem3/Solution.java
This gives the solution to problem 3 in the java problems.
> Solution to java-problem-3

- javaProblems/problem6/Solution.java
This gives solution to the problem 6 in JAVA problems.
> Solution to java problem 6

- javaProblems/problem5/Solution.java
This is the answer to the 5th problem in the java problems.
> Solution to java problem 5 

- notes/ssh.md
Added ssh.md which contains example usages of `ssh` command in bash.
> Added ssh.md

- javaProblems/problem31/Readme.md
- javaProblems/problem31/Solution.java
- javaProblems/problem31/Test.java
Added a Java solution for finding the Greatest Common Divisor (GCD) and the Lowest Common Multiple (LCM) of two integers as mentioned in #67 
Changes :
- Added a **`Solution.java`** file which contains the Solution for the given Problem
- Added a **`Test.java`** file which file includes a test suite that validates the solution for correctness. All test cases have passed successfully in My Testing
- Added a **`Readme.md`** file which explains the problem statement in detail
Deatils :
- Time Complexity - **`O(log n)`**
- Space Complexity - **`O(1)`**
> Add Solution for GCD and LCM Problem

- javaProblems/problem7/Readme.md
- javaProblems/problem7/Solution.java
- javaProblems/problem7/Test.java
Added a Java solution for determining if a given integer is a power of two as mentioned in #42 
- Added a `Solution.java` file which contains the solution for the given problem.
- Added a `Test.java` file which includes a test suite that validates the solution for correctness. All test cases have passed successfully in my testing.
- Added a `Readme.md` file which explains the problem statement in detail.
- Time Complexity - O(1)
- Space Complexity - O(1)
> Add Solution for Power of 2 Problem

- members/diwakar-gupta.md
Fixes #1 
This pr adds a new file `diwakar-gupta.md` inside folder [members](https://github.com/SST-OSS/club-onboarding/tree/main/members) that contains my github handle
> share my github handle

- README.md
**Summary:**
I've made some changes to this project that I believe would enhance its appearance. I've added a contributor badges section to the README.md file that displays badges for contributors. This makes it easier to showcase our project's contributors and praise them.
**Changes Made:**
- Added contributor badges section to README.md.
- Used GitHub Actions to automate the updating of contributor badges.
**How to Test:**
You can review the changes in the [README.md](https://github.com/PulsatingGenius/club-onboarding/blob/contributors/README.md) file of this branch. You should see the contributor badges displayed in an organized manner.
**Additional Notes:**
I'm open to any feedback or suggestions for further improvements. Please let me know if there are any specific changes you'd like …
> Adding-contributors-badges

- javaProblems/problem65/Solution.java
- javaProblems/problem65/Test.java
- javaProblems/problem65/readme.md
This pull request fixes the issue - [Add "find-greatest-common-divisor-of-array" Java Problem #65](https://github.com/SST-OSS/club-onboarding/issues/65).
In this PR:
- Added Solution.java
- Added readme.md
- Added Test.java
> Java Problem 65 - The GCD of Array Problem

- javaProblems/problem27/Solution.java
- javaProblems/problem27/Test.java
- javaProblems/problem27/readme.md
Added a Java solution for Sorting the Sentence in https://github.com/SST-OSS/club-onboarding/issues/63
Changes :
> Solved problem 27

- javaProblems/problem24/Solution.java
- javaProblems/problem24/Test.java
- javaProblems/problem24/readme.md
- problem24/Solution.java
- problem24/Test.java
- problem24/readme.md
test file updated according to requirement
fixes #60
> Java problem 24 , test file updated

- members/Om-Midya.md
- notes/basic-commands.md
Solved the issue #14 
changed the word "base" to "basic" in line 3.
> Fixing Documentation error #14

- members/abhinav26966.md
This PR fixes issue #1 by adding `abhinav26966.md` to members.
> created abhinav26966.md to add member abhinav to members folder.

- javaProblems/problem23/Solution.java
- javaProblems/problem23/Test.java
- javaProblems/problem23/readme.md
Added a Java solution for Sorting the Sentence in https://github.com/SST-OSS/club-onboarding/issues/59
Changes :
> solved problem23

- javaProblems/problem15/Solution.java
- javaProblems/problem15/Test.java
- javaProblems/problem15/readme.md
Added a Java solution for 10001st Prime in https://github.com/SST-OSS/club-onboarding/issues/51
Changes :
> solved problem15

- javaProblems/problem11/Solution.java
- javaProblems/problem11/Test.java
- javaProblems/problem11/readme.md
Added a Java solution for Find-the-index-of-the-first-occurrence-in-a-string in https://github.com/SST-OSS/club-onboarding/issues/47
Changes :
> solved problem11

- javaProblems/problem22/Solution.java
- javaProblems/problem22/Test.java
- javaProblems/problem22/readme.md
Added a Java solution for Kth distinct String in https://github.com/SST-OSS/club-onboarding/issues/58
Changes :
> solved problem22

- members/siddham-jain.md
> Siddham club onboarding

- members/harshit4311.md
> Harshit club onboarding

- javaProblems/problem21/Readme.md
- javaProblems/problem21/Solution.java
- javaProblems/problem21/Test.java
Added a Java solution for finding the smallest positive integer, x, such that 2x, 3x, 4x, 5x, and 6x contain the same digits as mentioned in #57 
- Added a `Solution.java` file which contains a method `findSmallestInteger()` that returns the smallest integer x satisfying the condition.
- Added a `Test.java` file which includes a test suite that validates the solution for correctness. The test case with the known answer 142857 has passed successfully in my testing.
- Added a `Readme.md` file which explains the problem statement in detail.
- Time Complexity - O(N)
- Space Complexity - O(1)
> Add Solution for `Permuted Multiples` Problem

- notes/basic-commands.md
Changes:
Corrected a spelling error in line 3 of `basic-commands.md` in notes folder.
Change was `base` to `basic`.
> Changed Line 3 spelling error in basic-commands.md

- notes/basic-commands.md
- notes/chmod.md
I have updated the `basic-commands.md` and `chmod.md` files in the `/notes` folder. The updates include fixing errors, typos and adding to the documentation.
> Documentation updates

- members/bishal-jena.md
Changes:
Added my name and github username in `bishal-jena.md` file inside members folder.
1 file change, 2 insertion.
> Add bishal-jena.md file to members

- members/neeldholiya04.md
reference issue #1 
added a file named neeldholiya04.md containig my name and github handle
> This adds neeldholiya04.md to the members directory

- members/Sushant9473.md
> club_onboarding
